import matplotlib.pyplot as pl
import numpy as np
import os
print(os.path.exists("Z:/datasets/train/Answer_data/0.data.npy"))
abc=np.load("Z:/datasets/train/Answer_data/129.data.npy")
data_E=np.load("Z:/datasets/train/Source_data/129.data.npy")[1:]

pl.subplot(6,1,5)
aba=np.abs(abc[1:,:,0]-data_E[:,:,0]).transpose((1,0))
pl.imshow(aba,aspect="auto",cmap="GnBu")
pl.clim(0,6)
pl.colorbar()
pl.subplot(6,1,2)
abn=np.transpose(abc[1:,:,0],(1,0))
pl.imshow(abn,aspect="auto")
pl.clim(-30,10)
pl.colorbar()
pl.subplot(6,1,6)
aba=np.abs(abc[1:,:,1]-data_E[:,:,1]).transpose((1,0))
pl.imshow(aba,aspect="auto",cmap="GnBu")
pl.clim(0,3.141592)
pl.colorbar()
pl.subplot(6,1,4)
abn=np.transpose(abc[1:,:,1],(1,0))
pl.imshow(abn,aspect="auto")
pl.clim(-3.141592,3.141592)
pl.colorbar()
pl.subplot(6, 1, 1)
data_E=data_E.reshape([-1,1024,2])
abn = np.transpose(data_E[1:, :, 0], (1, 0))
pl.imshow(abn, aspect="auto")
pl.clim(-30, 10)
pl.colorbar()
pl.subplot(6, 1, 3)
aba = data_E[:, :, 1].transpose((1, 0))
pl.imshow(aba, aspect="auto")
pl.clim(-3.141592, 3.141592)
pl.colorbar()

pl.show()